<?php
error_reporting(E_ALL);
// $functions = basename($_SERVER['PHP_SELF']); 
$baseUrl = "https://softyfier.com/project/website/douglasbrownlaw/";
$functions = basename($_SERVER['PHP_SELF']); // Get just the filename
switch ($functions) {
    case "index.php";
        $url = $baseUrl;
        $title_name = "Douglas D Brown";
        $description = "";
        $indexfollow = "index, follow";
        $keywordwords = "";
        break;
    case "about.php";
        $url = $baseUrl . "about";
        $title_name = "About | Douglas D Brown";
        $description = "";
        $indexfollow = "index, follow";
        $keywordwords = "";
        break;
    case "practice-areas.php";
        $url = $baseUrl . "practice-areas";
        $title_name = "Practice Areas | Douglas D Brown";
        $description = "";
        $indexfollow = "index, follow";
        $keywordwords = "";
        break;
    case "blogs.php";
        $url = $baseUrl . "blogs";
        $title_name = "Blogs | Douglas D Brown";
        $description = "";
        $indexfollow = "index, follow";
        $keywordwords = "";
        break;
    case "blog-single.php";
        $url = $baseUrl . "blog";
        $title_name = "Blogs Details | Douglas D Brown";
        $description = "";
        $indexfollow = "index, follow";
        $keywordwords = "";
        break;
    case "contact.php";
        $url = $baseUrl . "contact";
        $title_name = "Contact Us | Douglas D Brown";
        $description = "";
        $indexfollow = "index, follow";
        $keywordwords = "";
        break;
    case "family-law.php";
        $url = $baseUrl . "family-law";
        $title_name = "Family Law | Douglas D Brown";
        $description = "";
        $indexfollow = "index, follow";
        $keywordwords = "";
        break;
    case "personal-injury.php";
        $url = $baseUrl . "personal-injury";
        $title_name = "Personal Injury | Douglas D Brown";
        $description = "";
        $indexfollow = "index, follow";
        $keywordwords = "";
        break;
    case "adultery-divorce.php";
        $url = $baseUrl . "adultery-divorce";
        $title_name = "Adultery Divorce | Douglas D Brown";
        $description = "";
        $indexfollow = "index, follow";
        $keywordwords = "";
        break;
    case "criminal-defense.php";
        $url = $baseUrl . "criminal-defense";
        $title_name = "Criminal Defense | Douglas D Brown";
        $description = "";
        $indexfollow = "index, follow";
        $keywordwords = "";
        break;
    case "fedex-ups-amazon.php";
        $url = $baseUrl . "fedex-ups-amazon";
        $title_name = "FedEx, UPS, Amazon | Douglas D Brown";
        $description = "";
        $indexfollow = "index, follow";
        $keywordwords = "";
        break;
    case "criminalization-of-pregnancy.php";
        $url = $baseUrl . "criminalization-of-pregnancy";
        $title_name = "Criminalization of Pregnancy | Douglas D Brown";
        $description = "";
        $indexfollow = "index, follow";
        $keywordwords = "";
        break;
    case "know-more-about-douglas-brown.php";
        $url = $baseUrl . "know-more-about-douglas-brown";
        $title_name = "Know More About Douglas Brown | Douglas D Brown";
        $description = "";
        $indexfollow = "index, follow";
        $keywordwords = "";
        break;
    case "welcome-to-my-blog.php";
        $url = $baseUrl . "welcome-to-my-blog";
        $title_name = "Welcome To My Blog | Douglas D Brown";
        $description = "";
        $indexfollow = "index, follow";
        $keywordwords = "";
        break;
    case "when-an-attorney-is-your-client.php";
        $url = $baseUrl . "when-an-attorney-is-your-client";
        $title_name = "When an Attorney is Your Client | Douglas D Brown";
        $description = "";
        $indexfollow = "index, follow";
        $keywordwords = "";
        break;
    case "dont-be-your-own-lawyer.php";
        $url = $baseUrl . "dont-be-your-own-lawyer";
        $title_name = "Don't Be Your Own Lawyer | Douglas D Brown";
        $description = "";
        $indexfollow = "index, follow";
        $keywordwords = "";
        break;
}

$favIcon = 'https://hoisolution.com/dougbrownlaw/assets/imgs/favicon.png';
